version: "3.3"
services:
  keycloak_instance:
    image: "quay.io/keycloak/keycloak:15.0.2"
    ports:
      - "${DOCKER_PORT}:8080"
      - "9990:9990"
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    #restart: "unless-stopped"
