version: "3.3"
services:
  keycloak_instance:
    image: "quay.io/keycloak/keycloak:15.0.2"
    ports:
      - "${DOCKER_PORT}:8080"
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=${DB_VENDOR}
      - DB_ADDR=${DB_ADDR}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_FRONTEND_URL=${KEYCLOAK_FRONTEND_URL}
    restart: "unless-stopped"
